name: doc_test
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  injectable: ^1.0.4
  get_it: ^4.0.4
  provider: ^4.0.4

  logger: ^0.9.2
  supercharged: ^1.10.0

  intl: ^0.16.1
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2

  freezed_annotation:
  json_annotation: ^3.0.0

  dio: ^3.0.9
  retrofit: ^1.3.4

  cupertino_icons: ^1.0.0
  modal_bottom_sheet: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0

  build_runner:
  injectable_generator: ^1.0.4
  mobx_codegen: ^1.1.0+1
  freezed:
  json_serializable:
  retrofit_generator:


flutter:
  uses-material-design: true
  fonts:
    - family: Ubantu
      fonts:
        - asset: fonts/ubantu.ttf


flutter_intl:
  enabled: true
  main_locale: ru


